# -*- coding: utf-8 -*-
"""nlptrial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gGTJ-K2XnHTJ-ahF6A6arDX4z_7aBEPo
"""

import nltk
from textblob import TextBlob
from textblob import Word
#nltk.download('treebank')
#nltk.download('twitter_samples')
from nltk.corpus import twitter_samples
from nltk.book import *

#working on data twitter_samples (collection of tweets)

tweets = twitter_samples.strings('negative_tweets.json')

li=[]
for i in tweets:
  tweet=TextBlob(i)
  li.append(tweet.tags)     #using textblob to create a tag for each word in tweet collection ie noun, adjective tag etc

words=[]
for tweet in li:
    for pair in tweet:
        words.append(pair[0])   #creating a list of all the words in the tweets



wordstring=' '.join(words)    #converting words list to a string named wordstring
print("Collection of all words in form of a string: ",wordstring)

fdist1=FreqDist(words)
print("\n10 most common words and their frequencies: ",fdist1.most_common(10))   #most common words in wordstring using nltk
print('\nNo. of occurrences in wordstring of the word "aw": ',fdist1['aw'])   #no. of occurrences in wordstring of selected word using nltk
print("Percentage occurrence of the word 'aw'", fdist1['aw']*100/len(words),'%')

w=Word(li[1][3][0])  
print("\nLemmatising a selected word: ")
print('Original word: ',w)
print('Lemmatized word: ',w.lemmatize())    #using textblob for lemmatising ie extracting original form of word from selected word in list of tweets

adj_ctr=0
noun_ctr=0
adj=[]
noun=[]
for tweet in li:     #Finding total number of adjectives and nouns using tags in collection of tweets
    for pair in tweet:
        tag = pair[1]
        if tag == 'JJ':
            adj_ctr += 1
            adj.append(pair[0])
        elif tag == 'NN' or tag=='NNS':
            noun_ctr += 1
            noun.append(pair[0])


print('\nTotal number of adjectives in tweet collection= ', adj_ctr)
print("List of adjectives in tweet collection: ",adj)
print('\nTotal number of nouns in tweet collection= ', noun_ctr, noun)  
print("List of nouns in tweet collection: ",noun)



#working on string entered manually
st="I amm an ostrich and nobody can see me, not even I myself."
st2="It's so sad that turtles can only walk slow."
st3="Not being smart and amazing is not worst thing in the world."
blob=TextBlob(st)
blob2=TextBlob(st2)
blob3=TextBlob(st3)
print('\nOriginal string: ',st)
print('Spell checked string: ',blob.correct())
print("Detecting language in above sentence...", blob.detect_language())
print(blob.translate(to='hi'))
if blob2.sentiment.polarity>0:
  print("\n'",st2,"'", 'is positive')
else:  
  print("\n'",st2,",", 'is negative')

if blob3.sentiment.polarity>0:
  print("\n'",st3,"'", 'is positive')
else:  
  print("\n'",st3,"'", 'is negative')